[project]
name = "medium-email"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "datetime>=6.0",
    "fastapi>=0.129.0",
    "selenium>=4.39.0",
    "tk>=0.1.0",
    "uvicorn>=0.41.0",
]
